### PR TITLE
Rework Java example as a Maven project

### PR DESCRIPTION
**Pull request by Bouncheck**
Reworked existing example to use maven to build.
Path to the bundle can be passed as an argument
and assembly plugin can be used to make a jar with needed dependencies (see README).

### CODE REVIEW

**Comment by Bouncheck** [comment]
I haven't tried running it with a bundle yet as I don't have any working bundle on me right now.
Let me know if something here should be changed or added.

**Comment by avelanarius** [comment]
ping @rjeczalik (I will also review it)

**Review by rjeczalik — APPROVED** [review]

**Comment by rjeczalik** [comment]
Thank you guys! @Bouncheck @avelanarius ❤️

**Comment by annastuchlik** [comment]
@rjeczalik @omrivardi @avelanarius @Bouncheck 
This PR is incomplete, as the example doesn't include TokeanAwarePolicy - see https://github.com/scylladb/siren-frontend/issues/3402.

You can either merge this PR and fix https://github.com/scylladb/siren-frontend/issues/3402 later, or @Bouncheck should update this PR before it is merged.

**Comment by annastuchlik** [comment]
Thanks @Bouncheck .

@rjeczalik @avelanarius Cloud your review this updated PR?

**Review by rjeczalik — APPROVED** [review]

**Pull request merged**
